# Generated by Django 2.2.9 on 2019-12-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homeconfig_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconfig',
            name='serv_url',
            field=models.CharField(default='my server', max_length=100),
        ),
    ]
