# Generated by Django 2.2.9 on 2019-12-29 06:31

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_homeconfig_serv_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', markdownx.models.MarkdownxField()),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('github_url', models.URLField(null=True)),
            ],
        ),
    ]
