# Generated by Django 2.2.9 on 2019-12-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20191229_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='showcase',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
