# Generated by Django 2.2.9 on 2019-12-29 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20191229_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.FileField(upload_to='pdf')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='education',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='choice',
            field=models.CharField(choices=[('E', 'education'), ('A', 'award'), ('P', 'projects')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
