# Generated by Django 2.2.9 on 2019-12-29 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20191229_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='date',
            new_name='date_begin',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
