# Generated by Django 2.2.9 on 2019-12-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20191229_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodata',
            name='footage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfoliodata',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliodata',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliodata',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
